apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-pv
  namespace: diplom
  labels:
    type: local
    k8s-app: app-dpdt
    gitlab: diplom

spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/pg_data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db
  name: pg-data-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 200M