apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  DB_HOST: ZGI=
  POSTGRES_DB: ZGphbmdvX3R1dG9yaWFs
  POSTGRES_PASSWORD: cmcqJmMkQl4mSVZZSjc4NzU=
  POSTGRES_USER: ZGphbmdv
  #SECRET_KEY: 
