apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: diplom
#  labels:
#    k8s-app: app
#    gitlab: diplom

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
        
    spec:
      containers:
        - name: app       
          image: mikhailrizhkin1/diplom:v1.1.
          command: [ '/bin/sh' ]
          args: ['-c', 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3003']
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_HOST

            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DEBUG

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key:  POSTGRES_PASSWORD