apiVersion: v1
kind: Service 
metadata:
  name: app
  namespace: diplom
#  labels:
#    k8s-app: app-dpdt
#    gitlab: diplom
#    app: app-dpdt

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3003
      nodePort: 30036
      protocol: TCP
  selector:
    app: app
  externalIPs:
    - 158.160.75.53
    - 158.160.18.130
